config/routes.rb
RailsCms::Application.routes.draw do
  get "users/index"

  resources :tags, :only => ["index", "show"]
  resources :authentications

  match '/auth/:provider/callback' => 'authentications#create'

  match '/logout' => 'authentications#logout'

  resources :posts do
    resources :comments
  end
  match '/home' => 'home#index', :as => "home"
  resources :users
  match '/users' => 'users#index'

  root :to => "authentications#logout"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  before_validation :clear_attachment
  validates :topic, :presence => true

  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_attached_file :attachment
  has_many :tags

  def related_tags
    self.tags.map {|tag| tag.name }.join(", ")
  end

  def can_be_edited_by?(user)
    not user.blank? and (user.id == user_id or user.is_moderator? or user.is_admin?)
  end

  def delete_attachment=(value)
    @delete_attachment = !value.to_i.zero?
  end

  def delete_attachment
    !!@delete_attachment
  end

  alias_method :delete_attachment?, :delete_attachment

  def clear_attachment
    self.attachment = nil if delete_attachment? && !attachment.dirty?
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, :dependent => :destroy


  def is_admin?
    category == "admin"
  end

  def is_moderator?
    category == "moderator"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?

private
  def current_user
    User.find(session[:current_user]) unless session[:current_user].blank?
  end

  def logged_in?
    not session[:current_user].blank?
  end

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def index
  end

  def create
  end

  def destroy
  end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @page_title = "User's List"
    @users      = User.all
  end

  def create
    facebook_result           = request.env["omniauth.auth"]

    uid = facebook_result['uid']

    user = User.find_by_uid(uid)
    if user
      flash[:notice]                  = "#{user.name} signed in successfully!"
    else
      user = User.create(:name => facebook_result['user_info']['name'],
                         :category => "general",
                         :provider => facebook_result['provider'],
                         :uid => uid)
      flash[:notice]                  = "New user #{user.name} signed up and signed in successfully!"
    end

    session[:current_user]    = user.id
    redirect_to "/posts"
  end

  def logout
    session[:current_user]          = ""
    redirect_to "/home"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page_title = "WACS-Home"
    @post       = Post.order("updated_at DESC").limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index

    if logged_in?
      @page_title = "#{current_user.name}'s Posts"
      @posts = current_user.posts
    else
      @page_title = "WACS - Blog"
      @posts = Post.order("created_at DESC")
    end

    respond_to do |format|
      format.html # kk.html.erb
      format.xml { render :xml => @posts }
    end
  end

  def show
    @post = Post.find(params[:id])
    @editable = (@post.user_id == current_user.id) if logged_in?
    @page_title = "Post on #{@post.topic}"

    respond_to do |format|
      format.html # kk.html.erb
      format.xml { render :xml => @post }
    end
  end

  def new
    if logged_in?
      @post = Post.new

      respond_to do |format|
        format.html # new.html.erb
        format.xml { render :xml => @post }
      end
    else
      redirect_to '/auth/facebook'
    end
  end

  def edit
    post = Post.find(params[:id])
    if  post.user_id == current_user.id
      @post = Post.find(params[:id])
    else
      flash[:notice] = "You are not authorised to edit this post"
      redirect_to '/posts'
    end

  end

  def create
    tags_from_view = params[:tags]
    tags_array = tags_from_view.split(/,/)
    @post = Post.new(params[:post])
    respond_to do |format|
      if @post.save

        tags_array.each do |tag|
          tag_obj = Tag.new
          tag_obj.name = tag.downcase.strip
          tag_obj.post_id = @post.id
          tag_obj.save
        end

        format.html { redirect_to(@post, :notice => "Post was successfully created. tags are #{tags_from_view}") }
        format.xml { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update

    @post = Post.find(params[:id])


    respond_to do |format|
      if @post.update_attributes(params[:post])

        @post.tags.destroy_all

        tags_from_view = params[:tags]
        tags_array = tags_from_view.split(/,/)

        tags_array.each do |tag|
          tag_obj = Tag.new
          tag_obj.name = tag.downcase.strip
          tag_obj.post_id = @post.id
          tag_obj.save
        end

        format.html { redirect_to(@post, :notice => "Post was successfully updated. ") }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.can_be_edited_by?(current_user)
      @post.destroy
    else
      flash[:notice] = "You are not authorised to delete this post"
      redirect_to :"/posts"
    end
    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml { head :ok }
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @searched_tag = params[:id]
    @tags = Tag.where("name = ?",@searched_tag)
  end

  def index
    @tag_list = Tag.select("DISTINCT(name)")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if session[:current_user_category] == "admin"
      @list_users = User.all
    else
      redirect_to ('/home', :notice => 'You are not authorized to view this page')
    end
  end

  def edit
    if session[:current_user_category] == "admin"
      @user = User.find(params[:id])
    else
      redirect_to ('/home', :notice => 'You are not authorized to view this page')
    end
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to('/users', :notice => 'User was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    if session[:current_user_category] == "admin"
      @user = User.find(params[:id])
      @user.destroy
    else
      redirect_to ('/home', :notice => 'You are not authorized to view this page')
    end
    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentications/create.html.erb
<h1>Authentications#create</h1>
<p>Find me in app/views/authentications/create.html.erb</p>

app/views/authentications/destroy.html.erb
<h1>Authentications#destroy</h1>
<p>Find me in app/views/authentications/destroy.html.erb</p>

app/views/authentications/index.html.erb
<%= link_to 'Home', "/" %>
<h3>Listing Users</h3>

<table>
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th>Category</th>
    <th>User Id</th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.created_at.strftime('%d-%m-%Y') %> </td>
        <td><%= user.name %></td>
        <td><%= user.category %></td>
        <td><%= user.uid %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
  <b>&nbsp; on &nbsp;</b>
  <%= time_ago_in_words(comment.created_at) %>
</p>
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
              :confirm => 'Are you sure ?',
              :method  => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h2>Recent Activities</h2>
<div id="content">
  <% @post.each do |post| %>
      <div class="post">
        <p class="meta"><%= post.user.name %>
          <%= time_ago_in_words(post.created_at) %> before.</p>

        <h2 class="title"><%= post.topic %></h2>

        <div class="entry">
              <p><%= truncate(post.content, :length => 250, :omission => "...") %></p>
        </div>
        <div class="full_story"><%= link_to 'View Full Story', post, :class => "links" %></div>
      </div>
  <% end %>
</div>
<div id="sidebar">
  <ul>
    <li>
      <h2>What is WACS</h2>

      <p>An online content sharing platform for technical
        studies.
        Response to an immediate real­world problem.
        Those who can and wish to, does it best. eg:
        Wikipedia
        Very small learning curve.
      </p>
    </li>
    <li>
      <h2>Pellenteque ornare </h2>
      <ul>
        <li><a href="#">Nec metus sed donec</a></li>
        <li><a href="#">Magna lacus bibendum mauris</a></li>
        <li><a href="#">Velit semper nisi molestie</a></li>
        <li><a href="#">Eget tempor eget nonummy</a></li>
        <li><a href="#">Nec metus sed donec</a></li>
        <li><a href="#">Velit semper nisi molestie</a></li>
        <li><a href="#">Eget tempor eget nonummy</a></li>
        <li><a href="#">Nec metus sed donec</a></li>
      </ul>
    </li>
    <li>
      <h2>Turpis nulla</h2>
      <ul>
        <li><a href="#">Nec metus sed donec</a></li>
        <li><a href="#">Magna lacus bibendum mauris</a></li>
        <li><a href="#">Velit semper nisi molestie</a></li>
        <li><a href="#">Eget tempor eget nonummy</a></li>
        <li><a href="#">Nec metus sed donec</a></li>
        <li><a href="#">Nec metus sed donec</a></li>
        <li><a href="#">Magna lacus bibendum mauris</a></li>
        <li><a href="#">Velit semper nisi molestie</a></li>
        <li><a href="#">Eget tempor eget nonummy</a></li>
      </ul>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "WACS" %>   </title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="header">
  <div id="logo">
    <h1><%= link_to "WACS", "/" %></h1>

    <p><em> Web-enabled Content System</em></p>
  </div>
  <hr/>
  <!-- end #logo -->
  <div id="menu">

    <ul>
      <li><%= link_to "Home", home_path %></li>
      <li class="current_page_item"><%= link_to "Blog", posts_path %></li>
      <li><%= link_to "Tags",tags_path %> </li>
      <% if logged_in? && current_user.is_admin? %>
          <li><%= link_to 'Users', '/users' %></li>
      <% end %>
      <% if logged_in? %>
          <li><%= link_to 'Logout', '/logout' %></li>
      <% else %>
          <li> <%= link_to 'Login', "/auth/facebook" %></li>
      <% end %>
    </ul>
  </div>
</div>
<div id="wrapper">
  <div id="wrapper-bgtop">
    <div id="page">


      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </div>
</div>

<div id="footer-bgcontent">
  <div id="footer">
    <p>Copyright &copy; 2011. All rights reserved. Design by</p>
  </div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => {:multipart => true}) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>
    <div class="field">
      <%= f.label :topic %>
      <br/>
      <%= f.text_field :topic %>
    </div>
    <div class="field">
      <%= f.label :content %>
      <br/>
      <%= f.text_area :content %>
    </div>
    <% unless @post.new_record? || !@post.attachment? %>
        <div class="field">
          <%= f.label(:delete_attachment, 'Delete attachment') %>
          <br/>
          <%= @post.attachment_file_name %>
          <%= f.check_box :delete_attachment %>
        </div>
    <% end %>
    <div>
      <%= f.label :Attachment %>
      <br/>
      <%= f.file_field :attachment %>
    </div>
    <div class="field">
      <%= label_tag :tags %>
      <%= text_field_tag :tags, @post.related_tags %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h3>Listing posts</h3>

<table>
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th>Topic</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @posts.each do |post| %>
      <tr>
        <td><%= post.created_at.strftime('%d-%m-%Y') %> </td>
        <td><%= post.user.name %></td>
        <td><%= post.topic %></td>
        <td><%= truncate(post.content, :length => 70, :omission => '...') %></td>
        <td><%= link_to 'Show', post %></td>
        <% if post.can_be_edited_by?(current_user) %>
            <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
  <% end %>
</table>
<br/>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Date:</b>
  <%= @post.created_at.strftime("%d-%m-%Y") %>
</p>
<p>
  <b>Name:</b>
  <%= @post.user.name %>
</p>

<p>
  <b>Topic:</b>
  <%= @post.topic %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
<% if @post.attachment_file_name && @post.attachment_file_name != "" %>
    <p>
      <b>Attachments: </b>
      <%= link_to @post.attachment_file_name, @post.attachment.url %>
    </p>
<% end %>

<p>
  <b>Tags:</b>
  <% @post.tags.each do |tag| %>
  <%= link_to tag.name, tag_path(tag.name) %>
  <% end %>
</p>
<h2>Comments</h2>
<%= render :partial    => "comments/comment",
           :collection => @post.comments %>

<h2>New Comments:</h2>
<%= render "comments/form" %>
<% if @editable %>
    <%= link_to 'Edit',edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

app/views/tags/index.html.erb
<h3>You have reached Tag List</h3>
<% @tag_list.each do |tags| %>
    <%= link_to tags.name, "tags/#{tags.name}" %><br />
<% end %>

app/views/tags/show.html.erb
<h1><%= @searched_tag %> </h1>         <br/>

<ul>
  <% @tags.each do |tag| %>
     <li> <%= link_to tag.post.topic, tag.post %> </li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :name %>
      <br/>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :category %>
      <br/>
      <%= f.radio_button 'category','moderator' %> Moderator
      <%= f.radio_button 'category','general' %> General
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th></th>
    <th></th>
  </tr>
  <% @list_users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.category %></td>
        <% if session[:current_user_category] == "admin" %>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
      </tr>
  <% end %>
</table>